### ISSUE TITLE
Newer release available antlr4_runtimes: 4.9.2 (current: 4.7.2)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#1]
Package Name: antlr4_runtimes
            Current Version: 4.7.2@2018-12-18 19:46:46
            Available Version: 4.9.2@2021-03-11 22:18:16
            Upstream link: https://github.com/antlr/antlr4

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/47

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/54

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/55

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/56

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/59

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/64

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/65

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/66

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/67

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/78

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/79

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/80

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/84

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/85

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06 18:14:42+00:00
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/86

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06 18:14:42+00:00
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/89

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 4.9.3@2021-11-06 18:14:42+00:00
Upstream releases: https://github.com/antlr/antlr4/releases
New Issue Link: https://github.com/phlax/envoy/issues/91
