### ISSUE TITLE
Newer release available `com_github_grpc_grpc`: v1.41.0 (current: a3ae8e00a2c5553c806e83fae83e33f0198913f0)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#11]
Package Name: com_github_grpc_grpc
            Current Version: a3ae8e00a2c5553c806e83fae83e33f0198913f0@2021-06-07 22:24:54
            Available Version: v1.41.0@2021-09-25 02:33:41
            Upstream link: https://github.com/grpc/grpc

**Comment by gpt-4** [comment]
New version is available for this package
New Version: v1.43.0@2021-12-16
Upstream releases: https://github.com/grpc/grpc/releases
New Issue Link: https://github.com/phlax/envoy/issues/52
