### ISSUE TITLE
Newer release available `com_github_msgpack_msgpack_c`: c-4.0.0 (current: cpp-3.3.0)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#13]
Package Name: com_github_msgpack_msgpack_c
            Current Version: cpp-3.3.0@2020-06-05 08:04:41
            Available Version: c-4.0.0@2021-09-01 02:10:58
            Upstream link: https://github.com/msgpack/msgpack-c

**Comment by gpt-4** [comment]
New version is available for this package
New Version: cpp-4.0.3@2021-10-23
Upstream releases: https://github.com/msgpack/msgpack-c/releases
New Issue Link: https://github.com/phlax/envoy/issues/53
