### ISSUE TITLE
Newer release available `com_github_wamr`: WAMR-08-10-2021 (current: b554a9d05d89bb4ef28068b4ae4d0ee6c99bc9db)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#16]
Package Name: com_github_wamr
            Current Version: b554a9d05d89bb4ef28068b4ae4d0ee6c99bc9db@2021-07-06 09:05:59
            Available Version: WAMR-08-10-2021@2021-08-07 13:21:25
            Upstream link: https://github.com/bytecodealliance/wasm-micro-runtime

**Comment by gpt-4** [comment]
New version is available for this package
New Version: WAMR-12-30-2021@2021-12-30
Upstream releases: https://github.com/bytecodealliance/wasm-micro-runtime/releases
New Issue Link: https://github.com/phlax/envoy/issues/72
