### ISSUE TITLE
Newer release available `com_github_wasmtime`: v0.30.0 (current: v0.26.0)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#17]
Package Name: com_github_wasmtime
            Current Version: v0.26.0@2021-04-05 20:39:37
            Available Version: v0.30.0@2021-09-17 18:40:07
            Upstream link: https://github.com/bytecodealliance/wasmtime

**Comment by gpt-4** [comment]
New version is available for this package
New Version: v0.32.0@2021-12-13
Upstream releases: https://github.com/bytecodealliance/wasmtime/releases
New Issue Link: https://github.com/phlax/envoy/issues/60
