### ISSUE TITLE
Newer release available `com_github_zlib_ng_zlib_ng`: 2.0.5 (current: b802a303ce8b6c86fbe3f93d59e0a82333768c0c)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#18]
Package Name: com_github_zlib_ng_zlib_ng
            Current Version: b802a303ce8b6c86fbe3f93d59e0a82333768c0c@2020-10-18 13:39:11
            Available Version: 2.0.5@2021-06-25 17:35:43
            Upstream link: https://github.com/zlib-ng/zlib-ng

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 2.0.6@2021-12-24
Upstream releases: https://github.com/zlib-ng/zlib-ng/releases
New Issue Link: https://github.com/phlax/envoy/issues/61
