### ISSUE TITLE
Newer release available `edenhill_librdkafka`: v1.8.0 (current: v1.7.0)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#23]
Package Name: edenhill_librdkafka
            Current Version: v1.7.0@2021-05-10 09:28:20
            Available Version: v1.8.0@2021-09-15 19:46:12
            Upstream link: https://github.com/edenhill/librdkafka

**Comment by gpt-4** [comment]
New version is available for this package
New Version: v1.6.2@2021-11-17
Upstream releases: https://github.com/edenhill/librdkafka/releases
New Issue Link: https://github.com/phlax/envoy/issues/71
