### ISSUE TITLE
Newer release available `com_github_fmtlib_fmt`: 8.0.1 (current: 7.0.3)

### ISSUE THREAD

**Issue by phlax** [phlax/envoy#6]
Package Name: com_github_fmtlib_fmt
            Current Version: 7.0.3@2020-08-07 13:39:57
            Available Version: 8.0.1@2021-07-02 23:14:33
            Upstream link: https://github.com/fmtlib/fmt

**Comment by gpt-4** [comment]
New version is available for this package
New Version: 8.1.0@2022-01-02
Upstream releases: https://github.com/fmtlib/fmt/releases
New Issue Link: https://github.com/phlax/envoy/issues/81
